### ISSUE TITLE
When selecting Postgres Driver and PGVector dependencies, should only generate one pgvector DB, when used with Docker Compose support

### ISSUE THREAD

**Issue by dashaun** [spring-io/start.spring.io#1458]
Example compose.yaml

```yaml
services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
```

The label on the pgvector service even says "postgres" I think we should assume that the user only wants one database.

In this case we should remove the "postgres" service from the compose.yaml that gets delivered.
