### ISSUE TITLE
Upgrade to Okta Spring 1.3.0

### ISSUE THREAD

**Issue by bdemers** [spring-io/start.spring.io#304]
For Boot 2.1.x the version should remain `1.2.3`

I'm not 100% sure of the syntax, but I'm guessing

```yaml
          compatibilityRange: 2.1.2.RELEASE
          mappings:
            - compatibilityRange: "[2.1.2.RELEASE,2.2.0.RELEASE)"
              version: 1.2.3
            - compatibilityRange: "2.2.0.RELEASE"
              version: 1.3.0
```

Thanks!
